# Generated by Django 6.0.3 on 2026-09-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_snapshot',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='options_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_title_snapshot',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
