import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiFetch } from '../../../lib/apiFetch'
import Navbar from '../../../layout/Navbar'

type Address = { id: number; label: string; recipient_name: string; address: string; city: string; postal_code: string }

export default function ProfilePage() {
  const [profile, setProfile] = useState({ email: '', first_name: '', last_name: '' })
  const [addresses, setAddresses] = useState<Address[]>([])
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [address, setAddress] = useState({ label: 'Principal', recipient_name: '', address: '', city: '', state: '', postal_code: '', country: 'España', is_default: true })

  useEffect(() => { Promise.all([apiFetch('/auth/profile/'), apiFetch('/auth/addresses/')]).then(([user, saved]) => { setProfile(user as typeof profile); setAddresses(saved as Address[]) }).catch(() => setError('No se pudo cargar tu perfil.')) }, [])
  async function saveProfile(event: React.FormEvent) { event.preventDefault(); try { const result = await apiFetch('/auth/profile/', { method: 'PATCH', body: JSON.stringify(profile) }); setProfile(result as typeof profile); setMessage('Perfil actualizado.'); setError('') } catch { setError('No se pudo actualizar el perfil.') } }
  async function saveAddress(event: React.FormEvent) { event.preventDefault(); try { const result = await apiFetch('/auth/addresses/', { method: 'POST', body: JSON.stringify(address) }); setAddresses((current) => [...current, result as Address]); setMessage('Dirección guardada.'); setError('') } catch { setError('No se pudo guardar la dirección.') } }

  return <div className="min-h-screen bg-[#f8f7f2]"><Navbar /><main className="mx-auto max-w-4xl px-5 py-12"><Link to="/" className="text-sm text-slate-500">← Volver</Link><h1 className="mt-5 text-4xl font-semibold text-slate-950">Mi perfil</h1>{message && <p className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</p>}{error && <p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<section className="mt-8 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Datos personales</h2><form onSubmit={saveProfile} className="mt-4 grid gap-4 sm:grid-cols-2"><input value={profile.first_name} onChange={(event) => setProfile({ ...profile, first_name: event.target.value })} placeholder="Nombre" className="rounded-xl border px-3 py-3" /><input value={profile.last_name} onChange={(event) => setProfile({ ...profile, last_name: event.target.value })} placeholder="Apellidos" className="rounded-xl border px-3 py-3" /><input type="email" value={profile.email} onChange={(event) => setProfile({ ...profile, email: event.target.value })} placeholder="Correo" className="rounded-xl border px-3 py-3 sm:col-span-2" /><button className="rounded-xl bg-slate-950 px-4 py-3 font-semibold text-white sm:col-span-2">Guardar perfil</button></form></section><section className="mt-6 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Direcciones guardadas</h2>{addresses.map((item) => <div key={item.id} className="mt-3 rounded-xl border p-3 text-sm"><strong>{item.label}</strong> · {item.address}, {item.city}, {item.postal_code}</div>)}<form onSubmit={saveAddress} className="mt-5 grid gap-3 sm:grid-cols-2"><input required placeholder="Nombre del destinatario" value={address.recipient_name} onChange={(event) => setAddress({ ...address, recipient_name: event.target.value })} className="rounded-xl border px-3 py-3" /><input required placeholder="Dirección" value={address.address} onChange={(event) => setAddress({ ...address, address: event.target.value })} className="rounded-xl border px-3 py-3" /><input required placeholder="Ciudad" value={address.city} onChange={(event) => setAddress({ ...address, city: event.target.value })} className="rounded-xl border px-3 py-3" /><input required placeholder="Código postal" value={address.postal_code} onChange={(event) => setAddress({ ...address, postal_code: event.target.value })} className="rounded-xl border px-3 py-3" /><button className="rounded-xl border border-slate-950 px-4 py-3 font-semibold sm:col-span-2">Añadir dirección</button></form></section></main></div>
}
