# Generated by Django 4.2 on 2026-04-02 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
