# Generated by Django 6.0.3 on 2026-09-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_proof_note_payment_proof_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING_TRANSFER', 'Pending transfer'), ('PROOF_RECEIVED', 'Proof received'), ('MANUAL_CONFIRMED', 'Manual confirmed'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded')], max_length=20),
        ),
    ]
